server:
  port: 3344



spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangmingquuan/springboot-config-service.git #GitHub上面的git仓库名字
        ####搜索目录
          search-paths:
            - springboot-config-service
          force-pull: true
          username: 939550052@qq.com
          password: x1720033H
      ####读取分支
      label: master
#rabbitmq相关配置
#rabbitmq:
    #host: localhost
    #port: 5672
    #username: guest
    #password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
#management:
  #endpoints: #暴露bus刷新配置的端点
    #web:
      #exposure:
       # include: 'bus-refresh'


